Repository eslint/website, pull requests merged in 2019-09, with the labels that each got.

#619 Update: Added Coding Sans logo to "Who's using ESLint"
  _data/logos.yml
  assets/img/logos/codingsans.png
Labels: enhancement

#621 New: Indeed donation blog post
  _posts/2019-09-09-indeed-donates-10000-to-eslint.md
  assets/img/logos/indeed.svg
Labels: documentation

#622 Docs: Update release notes for eslint@6.4.0
  _posts/2019-09-13-eslint-v6.4.0-released.md
Labels: triage

#624 Chore: faraday@0.15.3 (work around netlify issue)
  Gemfile
Labels: triage

#623 Docs: Update 6.5.0 release notes
  _posts/2019-09-29-eslint-v6.5.0-released.md
Labels: documentation
