Repository eslint/website, pull requests merged in 2019-07, with the labels that each got.

#587 Added Openbravo logo to 'Who's using ESLint?' List
  _data/logos.yml
  img/logos/openbravo.svg
Labels: triage

#593 Fix: add Jekyll plugin to fix deployment preview URLs
  _config.yml
  _plugins/config_url.rb
Labels: bug, infrastructure

#591 fix broken links
  docs/4.0.0/rules/complexity.md
Labels: bug

#594 Fix: update logo paths
  Makefile
  README.md
  _data/logos.yml
  _posts/2019-02-12-funding-eslint-future.md
  assets/img/logos/README.md
  assets/img/logos/openbravo.svg
Labels: bug

#592 Fix Openbravo logo to be properly displayed in users page
  assets/img/logos/openbravo.svg
Labels: bug

#595 Chore: consolidate and bundle inline scripts
  _includes/footer.html
  _includes/header.html
  assets/js/image-lazy-loader.js
  demo/index.html
  package-lock.json
  package.json
  src/js/main/image-lazy-loader.js
  src/js/main/index.js
  users/index.md
  webpack.config.js
Labels: chore

#599 Update: add margin to sponsors rows
  src/styles/lib/sponsors.less
Labels: enhancement

#601 Chore: enable ES6+ rules and run autofixer
  .eslintrc.js
  src/js/demo/app.jsx
  src/js/demo/configuration.jsx
  src/js/demo/editor.jsx
  src/js/demo/environments.jsx
  src/js/demo/events.js
  src/js/demo/fixedCode.jsx
  src/js/demo/message.jsx
  src/js/demo/messages.jsx
  src/js/demo/parserOptions.jsx
  src/js/demo/rulesConfig.jsx
  src/js/demo/unicode.js
  src/js/main/image-lazy-loader.js
  src/js/main/index.js
  src/js/parser/index.js
  src/js/parser/lib.js
Labels: chore

#600 Chore: import bootstrap.native components in bundles
  _includes/footer.html
  package-lock.json
  package.json
  src/js/demo/configuration.jsx
Labels: chore

#598 Chore: use preset-env useBuiltIns option
  .babelrc
  src/js/demo/index.js
  src/js/main/index.js
  src/js/parser/index.js
  webpack.config.js
Labels: chore

#597 Consolidate pages in _pages directory
  README.md
  _config.yml
  _pages/404.md
  _pages/blog.html
  _pages/cla.md
  _pages/demo.html
  _pages/index.html
  _pages/parser.html
  _pages/team.md
  _pages/users.md
  docs/developer-guide/architecture/index.md
Labels: chore

#602 Revert "Chore: import bootstrap.native components in bundles (#600)"
  _includes/footer.html
  package-lock.json
  package.json
  src/js/demo/configuration.jsx
Labels: triage

#603 Chore: bundle bootstrap.native using webpack
  _includes/footer.html
  package-lock.json
  package.json
  src/js/demo/app.jsx
  src/js/demo/configuration.jsx
  src/js/main/index.js
Labels: chore

#604 Fix: set up Netlify redirect rules
  _config.yml
  _pages/cla.md
  _pages/index.html
  _redirects
  docs/0.24.1/command-line-interface/index.html
  docs/0.24.1/configuring/index.html
  docs/0.24.1/user-guide/integrations.md
  docs/0.24.1/user-guide/rules.md
  docs/1.0.0/command-line-interface/index.html
  docs/1.0.0/configuring/index.html
  docs/1.0.0/user-guide/integrations.md
  docs/1.0.0/user-guide/rules.md
  docs/1.10.3/command-line-interface/index.html
  docs/1.10.3/configuring/index.html
  docs/1.10.3/user-guide/integrations.md
  docs/1.10.3/user-guide/rules.md
  docs/2.0.0/command-line-interface/index.html
  docs/2.0.0/configuring/index.html
  docs/2.0.0/user-guide/integrations.md
  docs/2.0.0/user-guide/rules.md
  docs/2.13.1/command-line-interface/index.html
  docs/2.13.1/configuring/index.html
  docs/2.13.1/user-guide/rules.md
  docs/3.0.0/user-guide/rules.md
  docs/user-guide/rules.md
Labels: bug

#605 Fix: update files copied into _site
  CNAME
  _config.dev.yml
  _config.yml
Labels: bug

#606 Upgrade: update lodash in package-lock.json
  package-lock.json
Labels: upgrade

#607 Chore: remove Makefile
  Makefile
Labels: chore

#608 Chore: update .eslintrc.js
  .eslintrc.js
Labels: chore

#609 Upgrade: react & react-dom@16.8.6
  .eslintrc.js
  package-lock.json
  package.json
  src/js/demo/components/App.jsx
  src/js/demo/components/Configuration.jsx
  src/js/demo/components/Editor.jsx
  src/js/demo/components/Environments.jsx
  src/js/demo/components/FixedCode.jsx
  src/js/demo/components/Message.jsx
  src/js/demo/components/Messages.jsx
  src/js/demo/components/ParserOptions.jsx
  src/js/demo/components/RulesConfig.jsx
  src/js/demo/components/SelectAllCheckbox.jsx
  src/js/demo/index.js
  src/js/demo/messages.jsx
  src/js/demo/utils/events.js
  src/js/demo/utils/unicode.js
Labels: bug, upgrade

#610 Update JSCS link
  _posts/2016-04-14-welcoming-jscs-to-eslint.md
Labels: triage

#611 Update: Added MinuteMedia logo to 'Who's using ESLint? List'
  _data/logos.yml
  assets/img/logos/minutemedia.svg
Labels: triage
