Repository eslint/website, pull requests merged in 2019-11, with the labels that each got.

#644 Upgrade: eslint-utils@1.4.3
  package-lock.json
Labels: dependencies

#642 Update: Refresh homepage
  _includes/jumbotron.html
  _pages/index.html
  assets/img/jumbosplash.jpg
  src/styles/lib/bootstrap.less
Labels: enhancement

#645 New: November fundraising blog post update
  _posts/2019-11-07-funding-update.md
Labels: enhancement

#646 Update: Add sidebar to blog posts
  _layouts/post.html
  _pages/blog.html
Labels: design, enhancement

#648 Update: Add sponsor count and donation totals to homepage
  _pages/index.html
Labels: enhancement

#651 Update: Pull GitHub Sponsors donation data (fixes #647)
  _data/sponsors.json
  _tools/fetch-sponsors.js
  package-lock.json
  package.json
Labels: chore

#654 Docs: Update 6.7.0 release notes
  _posts/2019-11-22-eslint-v6.7.0-released.md
Labels: documentation

#655 Update 2019-11-22-eslint-v6.7.0-released.md
  _posts/2019-11-22-eslint-v6.7.0-released.md
Labels: triage

#657 Revert "Update: Pull GitHub Sponsors donation data (fixes #647)"
  _data/sponsors.json
  _tools/fetch-sponsors.js
  package-lock.json
  package.json
Labels: triage

#658 Update: Pull GitHub Sponsors donation data
  _tools/fetch-sponsors.js
  package-lock.json
  package.json
Labels: enhancement
