Repository eslint/website, pull requests merged in 2019-12, with the labels that each got.

#660 Docs: Fix broken link to eslint collective logo
  _posts/2019-02-12-funding-eslint-future.md
Labels: bug

#664 Update: remove parser demo
  _includes/menu.liquid
  _pages/parser.liquid
  package-lock.json
  src/js/espree.js
  src/js/parser/index.js
  src/js/parser/lib.js
  src/js/parser/parser.config.js
  webpack.config.js
Labels: accepted, demo, enhancement

#667 Update: update sponsor styles
  _pages/index.liquid
  src/styles/lib/sponsors.less
Labels: enhancement

#670 Upgrade: serialize-javascript vulnerability
  package-lock.json
Labels: dependencies

#665 Chore: bundle ESLint during build step
  .gitignore
  package-lock.json
  package.json
  src/js/demo/components/App.jsx
  src/js/demo/package.json
  src/js/eslint.js
  webpack.config.js
Labels: chore, infrastructure

#666 Update: add Platinum Sponsorship Tier
  _data/sponsors.json
  _pages/index.liquid
  _tools/fetch-sponsors.js
Labels: enhancement

#672 Chore: add analytics to sponsor links on home page
  _pages/index.liquid
  src/js/main/index.js
Labels: chore

#674 Add v6.8.0 release highlights
  _posts/2019-12-20-eslint-v6.8.0-released.md
Labels: triage

#673 Fix: update 2019-12-20-eslint-v6.8.0-released.md to fix liquid parsing error
  _posts/2019-12-20-eslint-v6.8.0-released.md
Labels: bug
