Repository eslint/website, pull requests merged in 2019-06, with the labels that each got.

#572 Docs: Update release notes for eslint@6.0.0-rc.0
  _posts/2019-06-09-eslint-v6.0.0-rc.0-released.md
Labels: triage

#573 Docs: make a URL a link.
  _posts/2019-06-09-eslint-v6.0.0-rc.0-released.md
Labels: triage

#571 Upgrade: fix vulnerabilities found by npm audit
  package-lock.json
  package.json
Labels: triage

#577 Chore: change gems to plugins in _config.yml (fixes #563)
  _config.yml
Labels: triage

#565 Lint: espree should be ignored
  .eslintignore
Labels: triage

#578 Chore: clean up dead code after DocSearch switch
  .gitignore
  .travis.yml
  _plugins/search.rb
  styles/less/search.less
  styles/main.css
  styles/main.css.map
Labels: chore

#580 Fix: syntax error in 2.0.0 valid-jsdoc (fixes #579)
  docs/2.0.0/rules/valid-jsdoc.md
Labels: bug

#581 Update blogpost for v6.0.0
  _includes/menu.html
  _posts/2019-06-21-eslint-v6.0.0-released.md
Labels: triage

#582 Fix: Demo now uses updated Linter access point (fixes eslint/eslint#11873)
  js/app/demo/app.jsx
Labels: accepted, bug, demo

#583 Fix: fix site name in title
  _includes/header.html
  feed.xml
Labels: bug

#585 Chore: Add Netlify status badge to README
  README.md
Labels: chore

#586 Enhancement: add Netlify badge to sponsors list
  index.html
Labels: enhancement
