Repository eslint/website, pull requests merged in 2019-08, with the labels that each got.

#612 Docs: Update release notes for eslint@6.2.0
  _posts/2019-08-18-eslint-v6.2.0-released.md
Labels: documentation

#614 Update 2019-08-20-eslint-v6.2.1-released.md
  _posts/2019-08-20-eslint-v6.2.1-released.md
Labels: triage

#616 Docs: fix wrong link
  _posts/2019-08-18-eslint-v6.2.0-released.md
Labels: bug, documentation

#613 New: add parser option for ES2020
  src/js/demo/components/ParserOptions.jsx
Labels: enhancement, evaluating
