Repository eslint/website, pull requests merged in 2019-10, with the labels that each got.

#628 Chore: fix badge URL
  README.md
Labels: chore

#627 Revert "Chore: faraday@0.15.3 (work around netlify issue) (#624)"
  Gemfile
Labels: upgrade

#632 Fix: deselect all doesn't deselect all checkboxes in ESLint demo
  src/js/demo/components/RulesConfig.jsx
Labels: accepted, bug, demo

#635 Fix: Popover doesn't hide after checking the rule
  src/js/demo/components/RulesConfig.jsx
Labels: bug, demo

#629 Update: Add ECMA Version 11 in parser demo
  src/js/parser/parser.config.js
Labels: demo, enhancement

#631 Update: handle crashes and report invalid autofix in ESLint demo
  src/js/demo/components/App.jsx
  src/js/demo/components/BugReport.jsx
  src/js/demo/components/Crash.jsx
Labels: demo, enhancement

#634 Chore: start:docker npm script
  README.md
  package.json
Labels: chore, infrastructure

#637 Update: use PureComponent and React.memo in configuration components
  src/js/demo/components/Configuration.jsx
  src/js/demo/components/Environments.jsx
  src/js/demo/components/ParserOptions.jsx
  src/js/demo/components/Rule.jsx
  src/js/demo/components/RulesConfig.jsx
Labels: demo

#639 Chore: use arrow functions as callbacks in JSX
  src/js/demo/components/App.jsx
  src/js/demo/components/Environments.jsx
  src/js/demo/components/Message.jsx
  src/js/demo/components/ParserOptions.jsx
  src/js/demo/components/SelectAllCheckbox.jsx
Labels: chore

#638 Fix: controlled to uncontrolled inputs warning (fixes #636)
  src/js/demo/components/Environments.jsx
  src/js/demo/components/ParserOptions.jsx
Labels: accepted, bug, demo

#640 Fix: recommended rules crash
  src/js/demo/components/App.jsx
Labels: triage

#641 Docs: Add highlights for 6.6.0 release
  _posts/2019-10-25-eslint-v6.6.0-released.md
Labels: documentation
