Repository eslint/website, pull requests merged in 2020-05, with the labels that each got.

#724 Fix: update foundation name in footer
  _includes/footer.liquid
Labels: bug

#723 Fix: remove empty Node.js and CommonJS category
  _data/rules.yml
Labels: bug

#720 Fix: use forced redirects in _redirects file
  public/_redirects
Labels: bug

#725 Docs: update ESLint v7.0.0 release notes
  _posts/2020-05-08-eslint-v7.0.0-released.md
Labels: documentation

#726 Docs: Add v7 migration guide to header menu
  _includes/menu.liquid
Labels: documentation, evaluating

#727 Fix: don't render links when plugin replaces core rule
  docs/rules/index.liquid
Labels: bug

#728 Docs: Change Markdown code fence to <code> tag
  docs/rules/index.liquid
Labels: bug

#729 Update: Code of conduct redirect
  public/_redirects
Labels: enhancement

#730 Update: Switch chat links to Discord (refs eslint/eslint#13029)
  _data/site.js
  _includes/footer.liquid
  docs/maintainer-guide/governance.md
  public/_redirects
Labels: enhancement

#732 New: Blog post announcing rules policies changes
  _posts/2020-05-22-changes-to-rules-policies.md
Labels: blog post

#733 Update logos.yml
  _data/logos.yml
  assets/img/logos/toptal.svg
Labels: triage
