Repository eslint/website, pull requests merged in 2020-08, with the labels that each got.

#761 Fix: Team data fetch (fixes #757)
  _data/team.json
  _tools/fetch-team-data.js
  package-lock.json
  package.json
Labels: accepted, bug, infrastructure

#759 Chore: switch to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: chore

#762 New: Salesforce donation announcement
  _posts/20202-08-06-salesforce-donates-10000-to-eslint.md
  assets/img/logos/salesforce.png
Labels: accepted, blog post

#764 Fix: Broken links in Salesforce donation blog post
  _posts/2020-08-06-salesforce-donates-10000-to-eslint.md
Labels: blog post

#765 New: Inclusivity post
  _posts/2020-08-10-making-eslint-more-inclusive.md
Labels: accepted, blog post

#767 New: Post announcing Microsoft donation
  _posts/2020-08-13-microsoft-donates-10000-to-eslint.md
  assets/img/logos/microsoft.png
Labels: accepted, blog post

#769 Docs: add v7.7.0 release highlights
  _posts/2020-08-14-eslint-v7.7.0-released.md
Labels: triage

#768 Chore: remove extra post file
  _posts/20202-08-06-salesforce-donates-10000-to-eslint.md
Labels: chore

#766 New: Add Ethical Ads
  _data/site.js
  _includes/ad.liquid
  _includes/head.liquid
  _includes/jumbotron.liquid
  _includes/text-ad.liquid
  _layouts/doc.liquid
  _layouts/post.liquid
  _layouts/rule.liquid
  _layouts/rules.liquid
  _pages/demo.liquid
  _pages/team.liquid
  _pages/users.liquid
  src/styles/lib/ad.less
  src/styles/main.less
Labels: accepted, enhancement

#770 New: GSoD post
  _posts/2020-08-19-eslint-google-season-of-docs-project-writer.md
Labels: accepted, blog post

#773 New: Roadmap blog post
  _posts/2020-08-28-eslint-public-roadmap.md
Labels: accepted, blog post

#776 Update: add ecmaVersion 2021 and es2021 environment to demo
  src/js/demo/components/App.jsx
  src/js/demo/components/ParserOptions.jsx
Labels: accepted, enhancement

#777 Docs: add highlights for v7.8.0
  _posts/2020-08-31-eslint-v7.8.0-released.md
Labels: triage
