Repository eslint/website, pull requests merged in 2020-04, with the labels that each got.

#710 Fix: Broken remaining broken links (refs #668)
  docs/2.0.0/developer-guide/working-with-rules.md
  docs/4.0.0/user-guide/formatters/html-formatter-example.html
  docs/4.0.0/user-guide/formatters/index.md
  docs/5.0.0/rules/index.md
  docs/6.0.0/rules/default-param-last.md
  docs/6.0.0/rules/function-call-argument-newline.md
  docs/6.0.0/rules/grouped-accessor-pairs.md
  docs/6.0.0/rules/index.liquid
  docs/6.0.0/rules/no-constructor-return.md
  docs/6.0.0/rules/no-dupe-else-if.md
  docs/6.0.0/rules/no-import-assign.md
  docs/6.0.0/rules/no-setter-return.md
  docs/6.0.0/rules/prefer-exponentiation-operator.md
  docs/6.0.0/rules/prefer-regex-literals.md
  docs/7.0.0/user-guide/configuring.md
  docs/maintainer-guide/governance.md
Labels: bug, documentation

#717 Docs: update ESLint v7.0.0-rc.0 release notes
  _posts/2020-04-24-eslint-v7.0.0-rc.0-released.md
Labels: documentation

#718 Docs: Add SwissDev JS Jobs to user showcase
  _data/logos.yml
  assets/img/logos/swissdev-javascript-jobs-logo.svg
Labels: triage

#722 Fix: Edit this page links
  _includes/footer.liquid
  _pages/404.liquid
  _pages/blog.liquid
  _pages/cla.md
  _pages/demo.liquid
  _pages/team.liquid
  _pages/users.liquid
Labels: bug
