Repository eslint/website, pull requests merged in 2020-09, with the labels that each got.

#778 Chore: sync `no-ads` with `master`
  _data/sponsors.json
  _posts/2020-08-31-eslint-v7.8.0-released.md
  docs/developer-guide/development-environment.md
  docs/developer-guide/nodejs-api.md
  docs/developer-guide/working-with-rules.md
  docs/maintainer-guide/releases.md
  docs/rules/id-length.md
  docs/rules/no-loss-of-precision.md
  docs/rules/no-magic-numbers.md
  docs/rules/object-curly-newline.md
  docs/rules/operator-assignment.md
  docs/user-guide/configuring.md
  docs/user-guide/formatters/html-formatter-example.html
  src/js/demo/components/App.jsx
  src/js/demo/components/ParserOptions.jsx
Labels: triage

#775 Fix: fetch only incoming orders from Open Collective in fetch-sponsors
  _data/sponsors.json
  _tools/fetch-sponsors.js
Labels: accepted, bug

#779 Chore: sync with master
  _data/sponsors.json
  _posts/2020-09-01-eslint-v7.8.1-released.md
  _tools/fetch-sponsors.js
  docs/user-guide/formatters/html-formatter-example.html
Labels: triage

#787 Sync with master branch
  _data/sponsors.json
  _posts/2020-09-12-eslint-v7.9.0-released.md
  docs/developer-guide/working-with-plugins.md
  docs/rules/no-await-in-loop.md
  docs/rules/no-return-await.md
  docs/user-guide/configuring.md
  docs/user-guide/formatters/html-formatter-example.html
  docs/user-guide/getting-started.md
  docs/user-guide/migrating-to-4.0.0.md
Labels: triage

#780 Update: Add rel=sponsored to sponsor links
  _pages/index.liquid
Labels: documentation, evaluating

#788 Sync no-ads with master branch
  _pages/index.liquid
Labels: triage

#782 Fix: reset unique header IDs per page (fixes #772)
  _11ty/plugins/markdown-plugins.js
Labels: triage

#789 New: Post about supporting our dependencies
  _posts/2020-09-16-supporting-eslint-dependencies.md
Labels: blog post

#792 Docs: add highlights for v7.10.0
  _posts/2020-09-26-eslint-v7.10.0-released.md
Labels: triage

#790 Update: use icons instead of text in the footer links (fixes #781)
  _includes/footer.liquid
Labels: triage
