Repository eslint/website, pull requests merged in 2020-07, with the labels that each got.

#744 Update: redirect id-blacklist -> id-denylist
  public/_redirects
Labels: accepted, enhancement

#745 Docs: Add v7.4.0 release highlights
  _posts/2020-07-03-eslint-v7.4.0-released.md
Labels: triage

#746 Update: Add technology sponsors to homepage
  _data/techsponsors.json
  _pages/index.liquid
  assets/img/logos/1password.png
  assets/img/logos/algolia.jpg
  assets/img/logos/netlify.png
Labels: triage

#748 Update: Add redirect for TSC meetings channel
  public/_redirects
Labels: triage

#750 Update: Add redirect for Discord help channel
  public/_redirects
Labels: enhancement

#751 Docs: Add v7.5.0 release highlights
  _posts/2020-07-18-eslint-v7.5.0-released.md
Labels: triage

#752 Update blogpost 7/18/20 2
  _posts/2020-07-18-eslint-v7.5.0-released.md
Labels: triage

#753 Docs: Fix typo in v7.5.0 release notes
  _posts/2020-07-18-eslint-v7.5.0-released.md
Labels: triage

#755 Fix: Ensure headings have IDs (fixes #747)
  _11ty/plugins/index.js
  _11ty/plugins/markdown-plugins.js
  package-lock.json
  package.json
Labels: triage

#758 Docs: Add v7.6.0 release highlights
  _posts/2020-07-31-eslint-v7.6.0-released.md
Labels: triage
