Repository eslint/website, pull requests merged in 2020-03, with the labels that each got.

#703 Fix: og:image
  _includes/head.liquid
Labels: accepted, bug

#705 Upgrade: fix security vulnerabilities
  package-lock.json
  package.json
Labels: dependencies, security, upgrade

#711 Update: Add housingAnywhere to Who's Using ESLint
  _data/logos.yml
  assets/img/logos/housinganywhere.svg
Labels: enhancement
