Repository eslint/website, pull requests merged in 2020-06, with the labels that each got.

#734 Update: add highlights to 7.2.0 release notes
  _posts/2020-06-05-eslint-v7.2.0-released.md
Labels: triage

#735 Update: Add banner
  _data/site.js
  _includes/menu.liquid
  _layouts/default.liquid
  _layouts/demo.liquid
  _layouts/doc.liquid
  _layouts/post.liquid
  _layouts/rule.liquid
  _layouts/rules.liquid
  src/styles/lib/banner.less
  src/styles/lib/overrides.less
  src/styles/main.less
Labels: enhancement

#738 Upgrade: update dependencies
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies

#740 Docs: Add v7.3.0 release highlights
  _posts/2020-06-19-eslint-v7.3.0-released.md
Labels: triage

#741 Docs: Added punctuation and link to license
  README.md
Labels: chore

#742 Docs: Add v7.3.1 release notes message
  _posts/2020-06-22-eslint-v7.3.1-released.md
Labels: triage

#743 Update: Add Atomist logo
  _data/logos.yml
  assets/img/logos/atomist.svg
Labels: triage
