Repository eslint/website, pull requests merged in 2020-02, with the labels that each got.

#690 Chore: install demo deps during build
  package.json
Labels: chore, infrastructure

#692 Fix: Show platinum sponsors on homepage (fixes #691)
  _data/sponsors.json
  _pages/index.liquid
  src/styles/lib/sponsors.less
Labels: accepted, bug

#696 Docs: Update v7.0.0-alpha.1 release notes
  _posts/2020-02-14-eslint-v7.0.0-alpha.1-released.md
Labels: triage

#697 Docs: fix category descriptions for site generation
  _data/rules.yml
  package-lock.json
Labels: bug

#698 New: Blog post announcing v7.0.0 features
  _posts/2020-02-20-whats-coming-in-eslint-7.0.0.md
Labels: accepted, documentation

#699 Fix: Broken link in 0.24.0 release notes (refs #668)
  _posts/2015-06-26-eslint-0.24.0-released.md
Labels: bug

#700 Docs: update ESLint v7.0.0-alpha.2 release notes
  _posts/2020-02-28-eslint-v7.0.0-alpha.2-released.md
Labels: triage
