Repository eslint/website, pull requests merged in 2020-01, with the labels that each got.

#676 Update: add es2017, es2020 on env names
  src/js/demo/components/App.jsx
Labels: demo, enhancement

#680 Upgrade: update dependencies
  .eleventy.js
  .eslintrc.js
  _11ty/filters/number-of-words.js
  _tools/dev-server.js
  _tools/yaml-to-json.js
  package-lock.json
  package.json
  src/js/demo/components/App.jsx
  webpack.config.js
Labels: upgrade

#682 Docs: Update 7.0.0-alpha.0 release notes
  _posts/2020-01-17-eslint-v7.0.0-alpha.0-released.md
Labels: documentation

#683 Fix: Broken rules links in 7.0.0-alpha.0 release notes
  _posts/2020-01-17-eslint-v7.0.0-alpha.0-released.md
Labels: documentation

#684 Chore: regenerate lockfile and make output less verbose
  package-lock.json
  package.json
Labels: chore

#681 Update: open demo rule links in new tab
  .eslintrc.js
  src/js/demo/components/Message.jsx
Labels: demo, enhancement
