Repository eslint/website, pull requests merged in 2021-09, with the labels that each got.

#868 Docs: add highlights for v8.0.0-beta.2
  _posts/2021-09-10-eslint-v8.0.0-beta.2-released.md
Labels: triage

#870 Chore: Update CI build badge in README
  README.md
Labels: triage

#872 Docs: add highlights for v8.0.0-rc.0
  _posts/2021-09-24-eslint-v8.0.0-rc.0-released.md
Labels: triage

#875 Chore: use `actions/setup-node@v2` in CI
  .github/workflows/ci.yml
Labels: accepted, chore

#876 Fix: use correct order frequency in `fetch-sponsors` script
  _tools/fetch-sponsors.js
Labels: bug, accepted
