Repository eslint/website, pull requests merged in 2021-12, with the labels that each got.

#889 feat: Post announcing Contra sponsorship
  _posts/2021-12-01-contra-gold-sponsor-eslint.md
  assets/img/logos/contra.jpg
Labels: blog post, feature

#890 docs: add highlights for v8.4.0
  _posts/2021-12-03-eslint-v8.4.0-released.md
Labels: accepted, documentation

#891 feat: explicitly specify if a rule is deprecated
  src/js/demo/components/Rule.jsx
  src/js/demo/components/RulesConfig.jsx
Labels: triage, feature

#892 chore: Update team data fetch
  _data/team.json
  _tools/fetch-team-data.js
Labels: accepted, chore

#893 docs: add author for v8.4.1
  _posts/2021-12-06-eslint-v8.4.1-released.md
Labels: triage, documentation

#896 docs: add highlights for v8.5.0
  _posts/2021-12-17-eslint-v8.5.0-released.md
Labels: documentation, blog post
