Repository eslint/website, pull requests merged in 2021-02, with the labels that each got.

#828 Docs: add highlights for v7.20.0
  _posts/2021-02-12-eslint-v7.20.0-released.md
Labels: triage

#830 Fix: Check for User and Organization sponsors (fixes #829)
  _tools/fetch-sponsors.js
Labels: accepted, bug

#832 Nx sponsorship announcement
  _posts/2021-02-18-nx-gold-sponsor-eslint.md
  assets/img/logos/nx.svg
Labels: accepted, blog post

#836 Docs: Add v7.21.0 release highlights
  _posts/2021-02-27-eslint-v7.21.0-released.md
Labels: triage
