Repository eslint/website, pull requests merged in 2021-07, with the labels that each got.

#856 Fix: update slugify function
  _11ty/plugins/markdown-plugins.js
Labels: accepted, bug

#857 Docs: add highlights for v7.30.0
  _posts/2021-07-02-eslint-v7.30.0-released.md
Labels: triage

#858 Docs: Use emojis instead of images to indicate fixable/recommended rules
  _layouts/doc.liquid
  _layouts/rules.liquid
  src/styles/lib/overrides.less
Labels: triage

#861 Docs: fix a broken link
  docs/rules/index.liquid
Labels: accepted, documentation

#860 Docs: Display emoji/notice for rules with suggestions
  _layouts/doc.liquid
  _layouts/rule.liquid
  _layouts/rules.liquid
  docs/rules/README.md
  docs/rules/index.liquid
  src/styles/lib/overrides.less
Labels: triage

#862 Docs: Add v7.32.0 release highlights
  _posts/2021-07-30-eslint-v7.32.0-released.md
Labels: triage
