Repository eslint/website, pull requests merged in 2021-03, with the labels that each got.

#835 Update: ecmaVersion default to 2021 in demo (fixes #508)
  src/js/demo/components/App.jsx
Labels: enhancement, evaluating

#834 Upgrade: webpack and loaders
  package-lock.json
  package.json
  webpack.config.js
Labels: accepted, upgrade

#838 Docs: add highlights for v7.23.0
  _posts/2021-03-26-eslint-v7.23.0-released.md
Labels: accepted, blog post
