Repository eslint/website, pull requests merged in 2022-02, with the labels that each got.

#912 chore: Add teaser property to remaining blog posts
  _posts/2014-11-15-es6-jsx-support.md
  _posts/2014-12-24-espree-esprima.md
  _posts/2016-04-19-eslint-joins-the-jquery-foundation.md
  _posts/2016-07-01-eslint-new-rule-format.md
  _posts/2016-07-15-jscs-end-of-life.md
  _posts/2018-07-12-postmortem-for-malicious-package-publishes.md
  _posts/2019-01-18-future-typescript-eslint.md
  _posts/2019-02-12-funding-eslint-future.md
  _posts/2019-05-01-funding-update.md
  _posts/2019-09-09-indeed-donates-10000-to-eslint.md
  _posts/2019-11-07-funding-update.md
  _posts/2020-08-06-salesforce-donates-10000-to-eslint.md
  _posts/2020-08-10-making-eslint-more-inclusive.md
  _posts/2020-08-13-microsoft-donates-10000-to-eslint.md
  _posts/2020-08-19-eslint-google-season-of-docs-project-writer.md
  _posts/2020-08-28-eslint-public-roadmap.md
  _posts/2020-09-16-supporting-eslint-dependencies.md
  _posts/2020-10-07-year-paying-contributors-review.md
  _posts/2020-12-10-automattic-platinum-sponsor-eslint.md
  _posts/2021-01-13-chrome-gold-sponsor-eslint.md
  _posts/2021-02-18-nx-gold-sponsor-eslint.md
  _posts/2021-12-01-contra-gold-sponsor-eslint.md
  package-lock.json
Labels: chore

#916 fix: Display authors with correct GitHub URL on blog posts
  _layouts/post.liquid
Labels: bug, accepted

#920 feat: Add totals to sponsors data file
  _data/sponsors.json
  _pages/index.liquid
  _tools/fetch-sponsors.js
Labels: accepted, feature

#922 chore: Add titles to team and author profiles
  _data/all_authors.json
  _data/team.json
  _tools/fetch-team-data.js
Labels: accepted, chore

#923 docs: add highlights for v8.9.0
  _posts/2022-02-11-eslint-v8.9.0-released.md
Labels: accepted, documentation

#928 docs: add highlights for v8.10.0
  _posts/2022-02-25-eslint-v8.10.0-released.md
Labels: accepted, documentation, blog post
