Repository eslint/website, pull requests merged in 2022-06, with the labels that each got.

#948 docs: add highlights for v8.17.0
  _posts/2022-06-03-eslint-v8.17.0-released.md
Labels: triage, documentation

#950 chore: Enable containers
  _11ty/plugins/markdown-plugins.js
  docs/rules/semi.md
  package-lock.json
  package.json
  src/styles/lib/overrides.less
Labels: accepted, chore

#951 docs: add highlights for v8.18.0
  _posts/2022-06-17-eslint-v8.18.0-released.md
Labels: triage, documentation

#952 ci: update github actions
  .github/workflows/ci.yml
Labels: triage, build
