Repository eslint/website, pull requests merged in 2022-04, with the labels that each got.

#931 docs: add author for v8.13.0
  _posts/2022-04-08-eslint-v8.13.0-released.md
Labels: accepted, documentation, blog post

#934 fix: check if blog post authors are specified in fetch-team-data script
  _posts/2022-03-25-eslint-v8.12.0-released.md
  _tools/fetch-team-data.js
Labels: bug

#935 docs: add highlights for v8.14.0
  _posts/2022-04-22-eslint-v8.14.0-released.md
Labels: accepted, documentation, blog post

#936 docs: fix heading in no-constant-binary-expression
  docs/rules/no-constant-binary-expression.md
Labels: triage, documentation

#937 Fixed typo in code comment
  docs/rules/no-constant-binary-expression.md
Labels: triage, documentation
