Repository eslint/website, pull requests merged in 2022-01, with the labels that each got.

#901 docs: Add v8.6.0 highlights
  _posts/2021-12-31-eslint-v8.6.0-released.md
Labels: triage, documentation

#902 chore: add teaser property to more posts
  _posts/2014-01-19-breaking-change-formatter.md
  _posts/2014-01-20-breaking-change-config-file.md
  _posts/2014-06-21-formatter-breaking-change.md
  _posts/2015-06-26-preparing-for-1.0.0.md
  _posts/2016-03-30-updated-rule-policy.md
  _posts/2016-04-14-welcoming-jscs-to-eslint.md
  _posts/2016-09-15-changes-to-issues-and-pr-policies.md
  _posts/2018-11-27-jsdoc-end-of-life.md
  _posts/2020-02-20-whats-coming-in-eslint-7.0.0.md
  _posts/2020-05-22-changes-to-rules-policies.md
  _posts/2021-06-08-whats-coming-in-eslint-8.0.0.md
Labels: triage, chore

#904 docs: fix wrong version in v8.0.1 teaser
  _posts/2021-10-13-eslint-v8.0.1-released.md
Labels: triage, documentation

#906 docs: Add v8.7.0 highlights
  _posts/2022-01-15-eslint-v8.7.0-released.md
Labels: triage, documentation

#910 docs: add highlights for v8.8.0
  _posts/2022-01-28-eslint-v8.8.0-released.md
Labels: accepted, documentation

#911 docs: fix typo in highlights for v8.8.0
  _posts/2022-01-28-eslint-v8.8.0-released.md
Labels: documentation

#909 docs: Correct un-grammatical typo
  docs/8.0.0/rules/no-ex-assign.md
Labels: accepted, documentation
