Repository eslint/website, pull requests merged in 2022-05, with the labels that each got.

#938 docs: add highlights for v8.15.0
  _posts/2022-05-06-eslint-v8.15.0-released.md
Labels: triage, documentation

#943 chore: Update rule docs format
  _layouts/doc.liquid
  docs/rules/block-scoped-var.md
  docs/rules/no-ternary.md
Labels: triage, chore

#944 docs: remove duplicate text
  _pages/users.liquid
Labels: triage, documentation

#945 docs: remove duplicate text
  _pages/team.liquid
Labels: triage, documentation

#947 docs: add highlights for v8.16.0
  _posts/2022-05-20-eslint-v8.16.0-released.md
Labels: triage, documentation

#946 fix: removes layout shift caused due to ads
  README.md
  src/styles/lib/ad.less
Labels: bug, triage
